devices:
  default:
    # uri: device/default
    color: true
    depth: true
    body:
      publish_body_markers: true
      frame_id: "quori/head_camera_optical"
      publish_tf: false
    # ir: true
    
